name: Test Suite

on:
  push:
    branches: [main]

jobs:
  tests:
    name: Smart Contract Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.11.1
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npx hardhat test

      - name: Run Coverage
        run: npx hardhat coverage        